###
@appName=heisconform-dev-5270b91
@azureApiUr=azurewebsites.net/api
@funcName=FirstContact
@code=4_z6dfsFbHF8U9ZMWnsq4aKA5PJ4shqdiYnULEj6rDwIAzFu5uvTtA==
POST https://{{appName}}.{{azureApiUr}}/{{funcName}}?code={{code}}&name=Homs