@startmindmap "System overview"
* System
** Tooling
*** Git
*** .NET c#
*** Docker
*** [[https://code.visualstudio.com/docs/devcontainers/containers devcontainers]]
*** [[https://github.com/nektos/act act - github workflows locally]]
*** [[https://github.com/coreybutler/nvm-windows/releases nvm-windows]] **(tested with v. 21.5.0)**
** Services
*** IaC
**** [[https://www.pulumi.com/ Pulumi]]
*****_ [[https://www.pulumi.com/registry/packages/azure/api-docs/appservice/functionapp/ App Function]]
*****_ [[https://www.pulumi.com/templates/static-website/azure/ Static Website]]
*** [[https://www.cloudflare.com CLOUDFLARE]]
****_ CAPTCHA
*** Azure
****_ App Function
****_ Static Website
****_ DNS
*** [[https://mailchimp.com MailChimp]]
****_ [[https://us8.admin.mailchimp.com/account/client-key/ Api key - Free (1000 mails/month)]]
*** [[https://github.com/ Github]]
**** Github actions
** Build and Deploy
*** [[https://nuke.build/ Nuke Build]]
*** [[https://learn.microsoft.com/en-us/rest/api/azure/ azure rest api]]
*** [[https://learn.microsoft.com/en-us/azure/azure-functions/deployment-zip-push zip deploy]]
** Automation
***_ Github actions

** Documentation
***_ MD
***_ [[https://plantuml.com/ Plantuml]]

@endmindmap