name: build-test-provision-deploy

permissions:
  contents: read

on:
  workflow_dispatch:
#on:
#  push:
#    branches:
#      - main

jobs:
  ubuntu-latest:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: |
          echo ${{ vars.FOO }}
          az webapp list --query "[?state=='Running']"
        env:
          ACTIONS_RUNNER_DEBUG: true
      - uses: actions/checkout@v3
      - name: 'Cache: .nuke/temp, ~/.nuget/packages'
        uses: actions/cache@v3
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}
      - name: 'Run: '
        run: ./build.cmd
        env:
          PulumiAccessToken: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AzureTenantId: ${{ secrets.AZURE_TENANT_ID }}
          AzureClientId: ${{ secrets.AZURE_CLIENT_ID }}
          AzureSubscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          PulumiStackName: ${{ vars.PULUMI_STACK_NAME }}
          PulumiOrganization: ${{ vars.PULUMI_ORGANIZATION }}
          ARM_USE_OIDC: ${{vars.ARM_USE_OIDC }}
