name: build-test-provision-deploy-v1

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:

jobs:
  ubuntu-latest:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: |
          echo ${{ vars.FOO }}
          az webapp list --query "[?state=='Running']"
        env:
          ACTIONS_RUNNER_DEBUG: true
      - uses: actions/checkout@v3
      - name: 'Cache: .nuke/temp, ~/.nuget/packages'
        uses: actions/cache@v3
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}
      - name: 'Run: '
        run: ./build.cmd
        env:
          PulumiAccessToken: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AzureSubscriptionId: ${{ fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId }}
          PulumiStackName: ${{ vars.PULUMI_STACK_NAME }}
          PulumiOrganization: ${{ vars.PULUMI_ORGANIZATION }}
          ARM_CLIENT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}
          ARM_CLIENT_SECRET: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientSecret }}
          ARM_TENANT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).tenantId }}
          ARM_SUBSCRIPTION_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId }}
          ARM_LOCATION_NAME: ${{ vars.ARM_LOCATION_NAME }}
